'use strict';
(()=>{
const D=window.SKZCampaignData, p=new URLSearchParams(location.search), worldId=p.get('world')||p.get('game'), gameId=p.get('mode')||p.get('game'), wi=Math.max(0,D.worlds.findIndex(w=>w.id===worldId)), W=D.worlds[wi], mi=Math.max(0,W.modes.findIndex(m=>m.id===gameId)), M=W.modes[mi], member=D.members.includes(p.get('char'))?p.get('char'):W.defaultChar;
document.documentElement.style.setProperty('--accent',W.accent);document.title=M.name+' | SYSTEM ERROR';
const $=id=>document.getElementById(id), canvas=$('game'),c=canvas.getContext('2d'),intro=$('intro'),result=$('result'),keys=new Set(),images={};
const load=(key,src)=>{const i=new Image();i.src=src;images[key]=i;return i};
const bg=load('bg',M.bg),mini=load('mini',`chars-w${wi+1}-${member}.webp`);load('hero',`member-art-${member}.webp`);load('roster',`roster-world-${wi+1}.webp`);
$('world-label').textContent=W.name;$('hud-game').textContent=M.name;$('objective').textContent=M.objective;$('controls-live').textContent='CONTROLS · '+M.controls;$('intro-title').textContent=W.name;$('intro-member').textContent=member.toUpperCase();$('intro-goal').textContent=M.objective;$('intro-controls').textContent=M.controls;
const hero=$('hero-art');hero.src=`member-art-${member}.webp`;$('world-echo').remove();$('roster-art').src=`roster-world-${wi+1}.webp`;
const S={x:110,y:440,vx:0,vy:0,ground:false,health:3,score:0,t:0,done:false,paused:false,phase:0,items:[],shots:[],enemies:[],platforms:[],lane:1,alert:0,combo:0,beat:0,gravity:1,fuel:100,charge:0,round:0,seq:[],seqAt:0,seqInput:[],last:0,dashAt:-10,lastInput:-10,beatAt:0,nextFlame:0,distance:0,selectedHeart:0,carry:0,dashUntil:0};
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function seed(){S.items=[];S.enemies=[];S.shots=[];S.platforms=[];S.t=0;S.score=0;S.health=3;S.done=false;S.x=110;S.y=430;S.vx=S.vy=0;S.phase=0;S.lane=1;S.alert=0;S.fuel=S.charge=100;S.round=0;S.seqAt=0;S.seqInput=[];S.dashAt=-10;S.lastInput=-10;S.beatAt=0;S.distance=0;S.selectedHeart=0;S.carry=0;S.dashUntil=0;
 const n=M.max||6;for(let i=0;i<n;i++){let x=300+i*105;S.items.push({x,y:rand(200,510),w:24,h:24,type:'item',got:false});}
 if(M.family==='kitchen')S.items=Array.from({length:3},(_,i)=>({x:260+i*170,y:455,w:30,h:30,type:['VEG','SPICE','NOODLE'][i],got:false}));
 for(let i=0;i<12;i++){S.platforms.push({x:i*100+120,y:480-(i%4)*62,w:100,h:16,dx:0,dy:0});}
 for(let i=0;i<Math.max(8,n);i++)S.enemies.push({x:350+i*105,y:rand(210,500),w:30,h:30,hp:1,vx:rand(-1,1),vy:0,kind:i%3});
 if(M.family==='climb'){S.y=480;S.platforms.forEach((v,i)=>{v.x=(i%2)*330+250;v.y=500-i*105;v.w=170;v.dy=i%2?-.4:.35});}
 if(M.family==='memory'){S.seq=Array.from({length:4},()=>Math.floor(rand(0,4)));S.seqAt=-1;}
}
seed();
const down=e=>{let k=e.key.toLowerCase(),first=!keys.has(k);keys.add(k);if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(first&&['rhythm','doit-runner','target-rush'].includes(M.family)){if(['a','arrowleft'].includes(k))S.lane=Math.max(0,S.lane-1);if(['d','arrowright'].includes(k))S.lane=Math.min(2,S.lane+1)}if(first&&M.family==='dual-track'){if(['arrowup','w'].includes(k))S.lane=0;if(['arrowdown','s'].includes(k))S.lane=1}if(first&&(k==='escape'||k==='p'))togglePause();if(first&&k==='q')phase();if(first&&(k==='e'||k==='j'||k==='x'||k==='enter'))action();if(first&&M.family==='heart-defense'&&['1','2','3'].includes(k))S.selectedHeart=Number(k)-1;if(first&&k===' '&&['rhythm','forest','heart-defense','karma'].includes(M.family)){if(M.family==='rhythm')phase();else if(M.family==='heart-defense')fire();else action()}if(first&&k===' '&&M.family==='titan'){S.x+=keys.has('a')||keys.has('arrowleft')?-90:90;S.dashAt=S.t}if(first&&k==='r'&&M.family==='memory')S.alert=0;if(first&&M.family==='memory'&&['arrowleft','arrowup','arrowright','arrowdown'].includes(k))memoryInput(['arrowleft','arrowup','arrowright','arrowdown'].indexOf(k));};
addEventListener('keydown',down);addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.querySelectorAll('#mobile-controls button').forEach(b=>{const key=b.dataset.key, on=e=>{e.preventDefault();keys.add(({left:'arrowleft',right:'arrowright',up:'arrowup',down:'arrowdown',jump:' ',action:'e',phase:'q',fire:'j'})[key]);if(['rhythm','doit-runner','target-rush'].includes(M.family)){if(key==='left')S.lane=Math.max(0,S.lane-1);if(key==='right')S.lane=Math.min(2,S.lane+1)}if(M.family==='dual-track'){if(key==='up')S.lane=0;if(key==='down')S.lane=1}if(key==='action')action();if(key==='phase')phase();if(key==='jump'&&M.family==='rhythm')phase();if(key==='jump'&&['forest','karma'].includes(M.family))action();if(key==='jump'&&M.family==='heart-defense')fire()};b.addEventListener('pointerdown',on);for(const n of ['pointerup','pointercancel','pointerleave'])b.addEventListener(n,()=>keys.delete(({left:'arrowleft',right:'arrowright',up:'arrowup',down:'arrowdown',jump:' ',action:'e',phase:'q',fire:'j'})[key]));});
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*960/r.width,y=(e.clientY-r.top)*600/r.height;if(M.family==='target-rush'){const t=S.items.find(v=>!v.got&&Math.abs(v.x-x)<70&&Math.abs(v.y-y)<65);if(t){t.got=true;S.score++;}}
 else if(['breach','soundwave','heart-defense','titan','boss'].includes(M.family))fire(x,y);else action();});
function action(){if(S.done||S.paused)return;if(M.family==='memory'){memoryInput(Math.floor(Math.random()*4));return}if(M.family==='kitchen'){if(S.x>790&&S.carry){S.carry=0;S.score++;toast('ORDER DELIVERED');return}const item=S.items.filter(v=>!v.got).sort((a,b)=>Math.abs(a.x-S.x)-Math.abs(b.x-S.x))[0];if(item&&Math.abs(item.x-S.x)<70){item.got=true;S.carry++;toast(item.type+' PICKED UP')}return}if(M.family==='gravity'){S.score++;toast('TERMINAL ACTIVATED');return}if(M.family==='karma'&&S.charge>=100){S.enemies.forEach(e=>e.hp=0);S.score=M.max;return}if(M.family==='forest')S.enemies.forEach(e=>e.stun=1.5);else if(['breach','soundwave','heart-defense','titan','boss'].includes(M.family))fire();else if(M.family==='target-rush'){const t=S.items.find(v=>!v.got);if(t){t.got=true;S.score++}}}
function fire(tx,ty){if(S.done)return;let x=S.x+20,y=S.y+15,vx=tx?clamp((tx-x)/30,-9,9):9,vy=ty?clamp((ty-y)/30,-7,7):0;if(M.family==='heart-defense'&&!tx&&!ty){vx=0;vy=-9}S.shots.push({x,y,vx,vy,w:18,h:10,life:1.6,heart:S.selectedHeart});}
function phase(){if(M.family==='gravity'){S.gravity*=-1;S.vy=0}else if(M.family==='quantum'||M.family==='boss'){S.phase^=1}else if(M.family==='rhythm'){if(Math.abs(S.t*2%1-.5)<.22)S.score++}else if(M.family==='karma'&&S.charge>=100)action();}
function memoryInput(i){if(S.seqAt<0){S.seqAt=0;return}S.seqInput.push(i);if(S.seqInput[S.seqInput.length-1]!==S.seq[S.seqInput.length-1]){S.seqInput=[];S.health--;toast('SEQUENCE ERROR · TRY AGAIN');return}if(S.seqInput.length===S.seq.length){S.score++;S.seqInput=[];S.round++;if(S.round>=3)win();else S.seq=Array.from({length:4+S.round},()=>Math.floor(rand(0,4)));}}
function toast(t){$('prompt').textContent=t;setTimeout(()=>$('prompt').textContent='',1500)}
function togglePause(){if(!intro.hidden)return;S.paused=!S.paused;$('pause').textContent=S.paused?'RESUME':'PAUSE';$('prompt').textContent=S.paused?'PAUSED · PRESS P OR RESUME':''}
$('pause').onclick=togglePause;$('begin').onclick=()=>{intro.hidden=true;canvas.focus();S.last=performance.now()};$('retry').onclick=()=>location.reload();$('continue').onclick=()=>{const all=W.modes.length, next=wi*3+mi+1, nxt=D.worlds.flatMap(w=>w.modes).at(next);if(nxt){const nw=D.worlds.find(w=>w.modes.includes(nxt));location.href=`campaign.html?world=${nw.id}&game=${nxt.id}&char=${member}`}else location.href='index.html#select'};
function win(){if(S.done)return;S.done=true;$('result').hidden=false;$('result-kicker').textContent='MISSION COMPLETE';$('result-title').textContent=M.name;$('result-grade').textContent=S.health>=2?'S':'A';$('result-copy').textContent='Sector secured. Your progress is saved; the next mission is now unlocked.';try{const old=JSON.parse(localStorage.getItem('skz.campaign.cleared')||'[]'),a=new Set(Array.isArray(old)?old:Object.keys(old).filter(k=>old[k]));a.add(M.id);localStorage.setItem('skz.campaign.cleared',JSON.stringify([...a]));}catch{}if(M.family==='boss'){$('result-kicker').textContent='SYSTEM RESTORED · CAMPAIGN FINALE';$('result-copy').textContent='The core is offline. The complete pixel roster joins the celebration.';$('final-rosters').hidden=false;$('final-rosters').querySelectorAll('img')[0].src='roster-world-8.webp';$('final-rosters').querySelectorAll('img')[1].src='roster-world-9.webp';$('continue').textContent='RETURN TO HUB';}}
function lose(){if(S.done)return;S.health--;if(S.health<=0){S.done=true;$('result').hidden=false;$('result-kicker').textContent='SIGNAL LOST';$('result-title').textContent='TRY AGAIN';$('result-grade').textContent='';$('result-copy').textContent='Your checkpoint is ready. Retry this mission to continue.'}}
function collide(){const player={x:S.x,y:S.y,w:32,h:40};for(const it of S.items)if(!it.got&&hit(player,{x:it.x,y:it.y,w:it.w,h:it.h})){it.got=true;S.score++;if(M.family==='karma')S.charge=clamp(S.charge+18,0,100)}for(const e of S.enemies)if(e.hp>0&&hit(player,e)&&M.family!=='stealth'){e.stun=.6;lose();S.vx=-S.vx;}}
function update(dt){S.t+=dt;let left=keys.has('a')||keys.has('arrowleft'),right=keys.has('d')||keys.has('arrowright'),up=keys.has('w')||keys.has('arrowup'),dn=keys.has('s')||keys.has('arrowdown'),jump=keys.has(' ')||up,runner=['momentum','rhythm-runner','target-rush','doit-runner','dual-track'].includes(M.family);
 if(M.family==='momentum'){
  S.vx=(right-left)*230;S.x=clamp(S.x+S.vx*dt,35,420);S.vy+=700*dt;if(jump&&S.ground){S.vy=-410;S.ground=false}
  if(keys.has('shift')&&S.t-S.dashAt>.7){S.dashAt=S.t;S.dashUntil=S.t+.36}const speed=S.t<S.dashUntil?470:235;S.distance+=speed*dt;
  for(const pl of S.platforms){pl.x-=speed*dt;if(pl.x+pl.w<0){pl.x=990;pl.y=440-Math.floor(rand(0,4))*48}}
  for(const it of S.items)it.x-=speed*dt;for(const e of S.enemies)e.x-=speed*dt;
 }
 else if(M.family==='rhythm-runner'){S.x+=220*dt;const base=dn?470:425;if(S.ground){S.y=base;if(jump){S.vy=-380;S.ground=false}}else{S.y+=S.vy*dt;S.vy+=780*dt;if(S.y>=base){S.y=base;S.vy=0;S.ground=true}}}
 else if(M.family==='climb'||M.family==='jetpack'){S.vx=(right-left)*250;S.vy+=520*dt;if(M.family==='jetpack'&&jump&&S.fuel>0){S.vy=-390;S.fuel-=45*dt}if(jump&&S.ground){S.vy=-360;S.ground=false}}
 else if(['breach','stealth','soundwave','gravity','quantum','boss'].includes(M.family)){S.vx=clamp(S.vx+(right-left)*540*dt,-250,250);S.vy+=700*dt;if(jump&&S.ground){S.vy=-400;S.ground=false}if(keys.has('shift')&&S.t-S.dashAt>.7){S.vx+=240;S.dashAt=S.t}S.x+=S.vx*dt;if(M.family==='stealth'&&dn)S.vx*=.94;}
 else if(['kitchen','forest','ice','titan','karma'].includes(M.family)){const friction=M.family==='ice'?.97:.82;S.vx=(S.vx+(right-left)*300*dt)*friction;S.vy=(S.vy+(dn-up)*300*dt)*friction;S.x+=S.vx*dt;S.y+=S.vy*dt;S.y=clamp(S.y,70,510)}
 else {S.vx=(right-left)*230;S.x+=S.vx*dt;if(jump&&S.ground){S.vy=-380;S.ground=false}S.vy+=700*dt;}
 S.x=clamp(S.x,15,M.family==='momentum'?420:920);if(M.family==='rhythm'||M.family==='target-rush'||M.family==='doit-runner'||M.family==='dual-track'){S.y=415+S.lane*55;S.vy=0;S.ground=true;let speed=keys.has('shift')&&S.t-S.dashAt>.7?500:220;if(speed===500){S.dashAt=S.t;S.dashUntil=S.t+.32}if(S.t<S.dashUntil)speed=500;S.x+=speed*dt;if(S.x>875){S.x=160;S.score++}}
 else {S.y+=S.vy*dt;S.ground=false;const floor=['climb','jetpack'].includes(M.family)?570:510;if(S.y>floor){S.y=floor;S.vy=0;S.ground=true}for(const pl of S.platforms){if(S.x+30>pl.x&&S.x<pl.x+pl.w&&S.vy*S.gravity>0&&S.y+40>pl.y&&S.y+40<pl.y+22){S.y=pl.y-40;S.vy=0;S.ground=true;if(M.family==='jetpack')S.fuel=100}if(M.family==='climb'){pl.y+=pl.dy*dt*60;if(pl.y<90||pl.y>550)pl.dy*=-1}}}
 if(M.family==='stealth'){let inLight=Math.abs((S.x+S.t*95)%500-240)<54&&S.y>330&&!dn;S.alert=clamp(S.alert+(inLight?dt*.34:-dt*.19),0,1);if(S.alert>=1){lose();S.alert=.3}}
 if(M.family==='rhythm'){if(S.beatAt<S.t){S.beatAt=S.t+.72;S.enemies.push({x:960,y:415+Math.floor(rand(0,3))*55,w:45,h:50,hp:1,kind:0,vx:-5})}}
 if(M.family==='rhythm-runner'&&S.beatAt<S.t){S.beatAt=S.t+.95;S.enemies.push({x:970,y:Math.random()<.5?390:485,w:42,h:45,hp:1,kind:0,vx:-5})}
 if(M.family==='kitchen'){if(S.t>(S.nextFlame||1.7)){S.nextFlame=S.t+2.4;S.enemies.push({x:rand(220,900),y:rand(370,500),w:34,h:45,hp:1,kind:2})}}
 if(M.family==='karma'&&Math.floor(S.t*1.4)!==S.beat){S.beat=Math.floor(S.t*1.4);S.enemies.push({x:480,y:300,w:18,h:18,hp:1,ring:true,r:8})}
 for(const e of S.enemies){if(e.hp<=0)continue;if(e.stun){e.stun-=dt;continue}if(e.ring){e.r+=130*dt;e.x=480+Math.cos(S.t+e.r/70)*e.r;e.y=300+Math.sin(S.t+e.r/70)*e.r;if(e.r>470)e.hp=0}else{e.x+=e.vx*dt*65;if(M.family!=='rhythm'&&(e.x<90||e.x>920))e.vx*=-1;if(M.family==='forest'){e.x+=Math.sign(S.x-e.x)*dt*18;e.y+=Math.sign(S.y-e.y)*dt*18}if(M.family==='ice')e.y+=Math.sin(S.t*2+e.x)*dt*55;}}
 for(const s of S.shots){s.x+=s.vx*dt*60;s.y+=s.vy*dt*60;s.life-=dt;for(const e of S.enemies)if(e.hp>0&&hit(s,e)){if(M.family!=='heart-defense'||e.kind===s.heart){e.hp=0;S.score++}s.life=0}}S.shots=S.shots.filter(s=>s.life>0&&s.x<980&&s.y>0&&s.y<600);S.enemies=S.enemies.filter(e=>e.hp>0||e.ring);
 if(M.family==='climb'&&S.t>2){S.y-=30*dt;S.x=clamp(S.x,80,870)}if(M.family==='jetpack'&&S.y<95){S.score=1;win()}
 if(M.family==='breach'&&S.score>=3)win();if(M.family==='soundwave'&&S.score>=10)win();if(M.family==='heart-defense'&&S.score>=M.max)win();if(M.family==='titan'&&S.score>=4)win();if(M.family==='boss'&&S.score>=M.max)win();if(M.family==='target-rush'&&S.score>=M.max)win();if(M.family==='forest'&&S.score>=M.max&&S.x>820)win();if(M.family==='ice'&&S.score>=M.max)win();if(M.family==='karma'&&S.score>=M.max&&S.charge>=100)win();if(M.family==='doit-runner'&&S.t>45)win();if(M.family==='dual-track'&&S.t>40)win();if(M.family==='rhythm'&&S.score>=M.max)win();if(M.family==='rhythm-runner'&&S.t>35)win();if(M.family==='kitchen'&&S.score>=M.max)win();if(M.family==='stealth'&&S.score>=M.max&&S.x>850)win();if(M.family==='gravity'&&S.x>850&&S.score>=1)win();if(M.family==='quantum'&&S.x>850&&S.score>=1)win();if(M.family==='momentum'&&S.t>30)win();if(M.family==='climb'&&S.y<80)win();if(M.family==='memory'&&S.round>=3)win();
 collide();$('hud-health').textContent='♥ '.repeat(Math.max(0,S.health));$('hud-progress').textContent=`${S.score} / ${M.max}`;$('hud-time').textContent=Math.max(0,Math.ceil((M.family==='kitchen'?75:60)-S.t))+'s';if(S.t> (M.family==='kitchen'?75:90)&&!S.done)lose();}
function draw(){c.clearRect(0,0,960,600);if(bg.complete&&bg.naturalWidth){c.drawImage(bg,0,0,960,600);c.fillStyle='#06112699';c.fillRect(0,0,960,600)}else{c.fillStyle='#101a39';c.fillRect(0,0,960,600)}
 c.fillStyle='#0b142b';c.fillRect(0,530,960,70);c.strokeStyle=W.accent;c.lineWidth=4;c.beginPath();c.moveTo(0,530);c.lineTo(960,530);c.stroke();
 for(const pl of S.platforms){c.fillStyle=M.family==='climb'?'#39dece':'#536b94';c.fillRect(pl.x,pl.y,pl.w,pl.h);c.fillStyle='#d9ffff';c.fillRect(pl.x,pl.y,pl.w,3)}
 for(const it of S.items)if(!it.got){c.fillStyle=M.family==='karma'?'#ffe477':'#4cf5e9';c.shadowColor=c.fillStyle;c.shadowBlur=15;c.fillRect(it.x,it.y,it.w,it.h);c.shadowBlur=0;c.fillStyle='#fff';c.fillRect(it.x+7,it.y+7,8,8)}
 for(const e of S.enemies){if(e.hp<=0)continue;c.fillStyle=e.ring?'#ff5899':M.family==='heart-defense'?['#ff75bf','#54e9ff','#ffe36c'][e.kind]:(e.kind===2?'#ff8d54':'#b96fff');if(e.ring){c.beginPath();c.arc(e.x,e.y,e.r||15,0,Math.PI*2);c.strokeStyle=c.fillStyle;c.lineWidth=7;c.stroke()}else c.fillRect(e.x,e.y,e.w,e.h)}
 for(const s of S.shots){c.fillStyle=M.family==='heart-defense'?['#ff75bf','#54e9ff','#ffe36c'][s.heart]:'#fff4a3';c.fillRect(s.x,s.y,s.w,s.h)}
 if(mini.complete&&mini.naturalWidth)c.drawImage(mini,S.x,S.y,40,48);else{c.fillStyle=W.accent;c.fillRect(S.x,S.y,34,42)}
 if(M.family==='stealth'){c.fillStyle=`rgba(255,215,80,${.12+Math.abs(Math.sin(S.t))*0.12})`;c.beginPath();c.moveTo((S.t*95)%960,0);c.lineTo((S.t*95)%960-100,500);c.lineTo((S.t*95)%960+100,500);c.fill();c.fillStyle='#fff';c.fillText('ALERT '+Math.round(S.alert*100)+'%',24,45)}
 if(M.family==='gravity'||M.family==='quantum'||M.family==='boss'){c.fillStyle=S.phase?'#ff64ae':'#4bd7ff';c.fillText(S.phase?'PINK PHASE':'BLUE PHASE',24,45)}if(M.family==='jetpack'){c.fillStyle='#fff';c.fillText('FUEL',24,45);c.fillStyle='#48e9da';c.fillRect(90,30,S.fuel*2,18)}if(M.family==='memory'){c.fillStyle='#fff';c.font='24px monospace';c.fillText(S.seqAt<0?'WATCH SEQUENCE · ← ↑ → ↓':`LOG ${S.round+1} · REPEAT ${S.seqInput.length}/${S.seq.length}`,250,75);if(S.seqAt<0){let q=Math.floor(S.t*1.1)%S.seq.length;c.fillText(['←','↑','→','↓'][S.seq[q]],460,280)}}if(M.family==='karma'){c.fillStyle='#fff';c.fillText('BLAST CHARGE '+S.charge+'%',24,45)}if(M.family==='rhythm'||M.family==='rhythm-runner'){c.fillStyle='#fff';c.beginPath();c.arc(480,90,22+Math.sin(S.t*8)*7,0,Math.PI*2);c.strokeStyle=W.accent;c.lineWidth=5;c.stroke()}
 c.fillStyle='#fff';c.font='18px monospace';c.fillText(`${M.name} · ${S.score} / ${M.max}`,24,580);if(M.family==='heart-defense')c.fillText(`HEART SHOT ${S.selectedHeart+1} · PRESS 1 / 2 / 3`,610,580);
 }
function loop(now){let dt=Math.min(.033,(now-(S.last||now))/1000);S.last=now;if(!S.paused&&intro.hidden&&!S.done)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
